{include file='common/header.phtml'}
<div id="main" class="container">
	<a id="page_content" name="page_content"></a> {literal}
	<style type="text/css">
#main .slideshow img {
	width: 920px;
	height: 520px !important;
}

#main .slideshow,#main .slideshow ul li {
	float: left;
	height: 520px !important;
}

#main .slideshow label {
	padding: 18px;
	height: 37px !important;
}

#main .slideshow a {
	top: -2px;
	font: 16px/22px 'DINHabitatReg', sans-serif;
}
</style>
	{/literal}

	<div class="slideshow">
		<ul>
			<li><a href="#" title="New SS14 Collection"> <img
					src="{$smarty.const.IMAGES}homepage/main_banner_hyde.jpg" />
			</a></li>
			<li class="white" style="border-bottom: 1px solid #000000"><a
				href="#" title="Fitted kitchens"> <img
					src="{$smarty.const.IMAGES}homepage/main_ban_kitchen.jpg" />
			</a></li>
		</ul>
	</div>

	<div class="feature">
		<strong>Free delivery</strong> on home accessory orders over &pound;50
		and on all orders over &pound;500** <strong>Free returns</strong> on
		all orders
	</div>

	<!--div class="carousel w4">
		<h2>
			<a href="#"  title="Nổi bật"> Favourites &raquo;</a>
		</h2>
		<div class="wrapper">
			<ul class="products">
				<li>
			</ul>
		</div>
	</div-->

	<div class="w2 h2 black">
		{$first = $topProduct[1]}
		<img src="{$smarty.const.HOST}upload/product/{$topOne.image}" />
		<label>
			<h2>{$topOne.product_name}</h2>
			<a	href="#" title="{$topOne.product_name}">detail &raquo;</a>
		</label>
	</div>

	<div class="w2 h1 black">
		<img src="{$smarty.const.HOST}/upload/product/{$topTwo.image}" />
		<label>
			<h2>{$topTwo.product_name}</h2>
			<a	href="#" title="{$topTwo.product_name}">detail &raquo;</a>
		</label>
	</div>

	<div class="w2 h1 black">
		<img src="{$smarty.const.HOST}/upload/product/{$topThree.image}" /> <label>
			<h2>{$topThree.product_name}</h2>
			<a	href="#" title="{$topThree.product_name}">detail &raquo;</a>
		</label>
	</div>
	{foreach key=i item=product from=$otherProducts}
	{if $product.holderSize=='11'}
		<div class="w1 h1 black">
		<img src="{$smarty.const.HOST}/upload/product/{$product.image}" /> <label>
			<h2>{$product.product_name}</h2> <a
			href="#"
			title="{$product.product_name}">detail &raquo;</a>
		</label>
	</div>	
	{/if}
	{if $product.holderSize=='21'}
		<div class="w2 h1 black">
		<img src="{$smarty.const.HOST}/upload/product/{$product.image}" /> <label>
			<h2>{$product.product_name}</h2> <a
			href="#"
			title="{$product.product_name}">detail &raquo;</a>
		</label>
	</div>
	{/if}
	{/foreach}
</div>
{include file='common/panel.phtml'}
{include file='common/footer.phtml'}