{include file='common/header.phtml'}

<div id="main" class="container">
	
	<div class="subfeature">
		<strong>Free delivery</strong> on home accessory orders over &pound;50
		and on all orders over &pound;500** <strong>Free returns</strong> on
		all orders
	</div>
	
	<div class="nw1 nh2 newsImage">
		<img src="{$smarty.const.IMAGES}news/mh370.jpg" />
		
	</div>
	
	<div class="w2 nh1 black newsTitle">
		<strong>Malaysia bác tin MH370 xuất hiện ở Maldives</strong>
	</div>
	
	<div class="w2 nh1 newsSum">
		Bộ trưởng Quốc phòng Malaysia hôm nay cho biết Maldives xác nhận thông tin về việc người dân thấy phi cơ lớn nghi là MH370 xuất hiện trong không phận quốc đảo này là không chính xác.
	</div>

</div>



{include file='common/footer.phtml'}
