{include file='common/header.phtml'}
<div id="main" class="container">
	{foreach key=i item=row from=$arrList}
		<div class="w2news h1 black">
			<img src="{$row.image}" alt="{$row.title}"/>
			<div class="newscontent">
				{$row.summary}
			</div>
			<label>
				<h2>{$row.title}</h2>
				<a href="{$utils->buildNewsSEOLink($smarty.const.HOST, $row.title, $row.id)}" title="{$row.title}">Ngày đăng: {$row.creationDate}</a>
			</label>
	</div>
	{/foreach}
</div>
{include file='common/panel.phtml'}
{include file='common/footer.phtml'}
