{include file='common/header.phtml'}

<div id="main" class="container">
	
	<div class="subfeature">
		<strong>Free delivery</strong> on home accessory orders over &pound;50
		and on all orders over &pound;500** <strong>Free returns</strong> on
		all orders
	</div>
	
		<div class="nw1 nh2 newsImage">
			<img src="{$smarty.const.IMAGES}news/mh370.jpg" />
			
		</div>
		
		<div class="w2 nh1 black newsTitle">
			<strong>Malaysia bác tin MH370 xuất hiện ở Maldives</strong>
		</div>
		
		<div class="w2 nh3 newsSum">
			Bộ trưởng Quốc phòng Malaysia hôm nay cho biết Maldives xác nhận thông tin về việc người dân thấy phi cơ lớn nghi là MH370 xuất hiện trong không phận quốc đảo này là không chính xác.
		</div>
		
		<div class="nw1 nh2 newsImage">
			<img src="{$smarty.const.IMAGES}news/vatthe.jpg" />
			
		</div>
		
		<div class="w2 nh1 black newsTitle">
			<strong>Radar Mỹ phát hiện vật thể 'cỡ lớn' dưới biển</strong>
		</div>
		
		<div class="w2 nh3 newsSum">
			Radar trên một máy bay trinh sát Mỹ phát hiện một thứ "cỡ lớn" dưới mặt nước phía nam Ấn Độ Dương, sau khi vệ tinh chụp được những vật thể có thể là mảnh vỡ của chuyến bay MH370 mất tích. 
		</div>
		

</div>



{include file='common/footer.phtml'}
