{include file='common/header.phtml'}
<div id="main" class="container">
	<div class="feature">
			Free delivery on home accessory orders over &pound;50 and on all orders over &pound;500** Free returns on all orders
	</div>
	<div class="w2 h2 black">
		<img src="{$smarty.const.HOST}upload/product/{$topOne.image}" />
		<label>
		<h2>{$topOne.productName}</h2>
		<a	href="{$utils->buildProjectDesignSEOLink($smarty.const.HOST, $topOne.productName, $topOne.id)}" title="Chi tiết thiết kế nội ngoại thất dự án {$topOne.productName}">detail &raquo;</a>
		</label>
	</div>

	<div class="w2 h1 black">
		<img src="{$smarty.const.HOST}upload/product/{$topTwo.image}" />
		<label>
		<h2>{$topTwo.productName}</h2>
		<a	href="{$utils->buildProjectDesignSEOLink($smarty.const.HOST, $topTwo.productName, $topTwo.id)}" title="Chi tiết thiết kế nội ngoại thất dự án {$topTwo.productName}">detail &raquo;</a>
		</label>
	</div>

	<div class="w2 h1 black">
		<img src="{$smarty.const.HOST}upload/product/{$topThree.image}" />
		<label>
		<h2>{$topThree.productName}</h2>
		<a	href="{$utils->buildProjectDesignSEOLink($smarty.const.HOST, $topThree.productName, $topThree.id)}" title="Chi tiết thiết kế nội ngoại thất dự án {$topThree.productName}">detail &raquo;</a>
		</label>
	</div>

{foreach key=i item=product from=$otherProjects}
	{if $product.imgType=='11'}
		<div class="w1 h1 black">
		<img src="{$smarty.const.HOST}/upload/product/{$product.image}" /> <label>
			<h2>{$product.productName}</h2>
			<a	href="{$utils->buildProjectDesignSEOLink($smarty.const.HOST, $product.productName, $product.id)}" title="Chi tiết thiết kế nội ngoại thất dự án {$product.productName}">detail &raquo;</a>
		</label>
	</div>	
	{/if}
	{if $product.imgType=='21'}
		<div class="w2 h1 black">
		<img src="{$smarty.const.HOST}/upload/product/{$product.image}" /> <label>
			<h2>{$product.productName}{$product.imgType}</h2>
			<a	href="{$utils->buildProjectDesignSEOLink($smarty.const.HOST, $product.productName, $product.id)}" title="Chi tiết thiết kế nội ngoại thất dự án {$product.productName}">detail &raquo;</a>
		</label>
	</div>
	{/if}
	{/foreach}
</div>
{include file='common/panel.phtml'}
{include file='common/footer.phtml'}
