{include file='common/header.phtml'}
<div id="main" class="container">
	<div class="w2 h2 black">
		<img src="{$smarty.const.IMAGES}homepage/merch_2x2_outdoor-insp.jpg" />
		<label>
			<h2>Outdoor inspiration</h2> <a
			href="{$smarty.const.HOST}projectdesign"
			onclick="_gaq.push(['_trackEvent', 'Homepage ', 'Click', 'merchspot a 2x2']); WaitForSeconds(0.25);"
			title="Outdoor inspiration">detail &raquo;</a>
		</label>
	</div>


	<div class="w2 h1 black">
		<img src="{$smarty.const.IMAGES}homepage/merch_2x1_bun.jpg" /> <label>
			<h2>Sit back and relax</h2> <a
			href="type/sofas/fcp-category/home.html"
			onclick="_gaq.push(['_trackEvent', 'Homepage ', 'Click', 'merchspot b 2x2']); WaitForSeconds(0.25);"
			title="Sit back and relax">detail &raquo;</a>
		</label>
	</div>

	<div class="w2 h1 black">
		<img src="{$smarty.const.IMAGES}homepage/2x1_lights.jpg" /> <label>
			<h2>Brighten up your space</h2> <a
			href="categories/lighting/fcp-category/home.html"
			onclick="_gaq.push(['_trackEvent', 'Homepage ', 'Click', 'merchspot c 2x2']); WaitForSeconds(0.25);"
			title="Brighten up your space">detail &raquo;</a>
		</label>
	</div>


	<div class="w1 h1 black">
		<img src="{$smarty.const.IMAGES}homepage/1x1_furniture.jpg" /> <label>
			<h2>Storage and shelving</h2> <a
			href="categories/storage/fcp-category/home.html"
			onclick="_gaq.push(['_trackEvent', 'Homepage ', 'Click', 'merchspot 2x1 – a']); WaitForSeconds(0.25);"
			title="Storage and shelving">detail &raquo;</a>
		</label>
	</div>

	<div class="w2 h1 black">
		<img src="{$smarty.const.IMAGES}homepage/2x1_lights.jpg" /> <label>
			<h2>Brighten up your space</h2> <a
			href="categories/lighting/fcp-category/home.html"
			onclick="_gaq.push(['_trackEvent', 'Homepage ', 'Click', 'merchspot c 2x2']); WaitForSeconds(0.25);"
			title="Brighten up your space">detail &raquo;</a>
		</label>
	</div>

	<div class="w1 h1 black">
		<img src="{$smarty.const.IMAGES}homepage/1x1_soft_furnishings.jpg" />
		<label>
			<h2>Beautiful rugs</h2> <a
			href="rugs-floor-coverings/furniture/fcp-category/list.html"
			onclick="_gaq.push(['_trackEvent', 'Homepage ', 'Click', 'merchspot 1x1 – a']); WaitForSeconds(0.25);"
			title=Beautifulrugs">detail &raquo;</a>
		</label>
	</div>

	<div class="w1 h1 black">
		<img src="{$smarty.const.IMAGES}homepage/1x1_pictureFrames.jpg" /> <label>
			<h2>Frames</h2> <a
			href="picture-frames/accessories/fcp-category/list.html"
			onclick="_gaq.push(['_trackEvent', 'Homepage ', 'Click', 'merchspot 1x1 – a']); WaitForSeconds(0.25);"
			title="Frames">detail &raquo;</a>
		</label>
	</div>

	<div class="w1 h1 black">
		<img src="{$smarty.const.IMAGES}homepage/1x1-Talia-Stools.jpg" /> <label>
			<h2>Practical stools</h2> <a
			href="stools/furniture/fcp-category/list.html"
			onclick="_gaq.push(['_trackEvent', 'Homepage ', 'Click', 'merchspot 1x1 – b']); WaitForSeconds(0.25);"
			title="Practical stools">detail &raquo;</a>
		</label>
	</div>

	<div class="w2 h1 black">
		<img src="{$smarty.const.IMAGES}homepage/2x1_lights.jpg" /> <label>
			<h2>Brighten up your space</h2> <a
			href="categories/lighting/fcp-category/home.html"
			onclick="_gaq.push(['_trackEvent', 'Homepage ', 'Click', 'merchspot c 2x2']); WaitForSeconds(0.25);"
			title="Brighten up your space">detail &raquo;</a>
		</label>
	</div>
</div>
{include file='common/footer.phtml'}
