{include file='common/header.phtml'}
<div id="main" class="designcontainer">
</div>
<div id="wrapperslide">
	<div id="bigPic">
		{foreach key=i item=image from=$productImages}
			<img src="{$smarty.const.HOST}/upload/product/{$image.file_name}" title="{$image.description}"/>
		{/foreach}
	</div>
	<ul id="thumbs">
		{foreach key=i item=image from=$productImages}
			<li {if $i+1==1}class='active'{/if} rel="{$i+1}">
				<img src="{$smarty.const.HOST}/upload_thumb/product/{$image.file_name}"/>
			</li>
		{/foreach}
	</ul>
</div>
<div id="main" class="container">
	<br>
	<h2>Dự Án: {$productDetails.product_name}<hr></h2>
	<br>
	<h4>Chủ Dự Án: {$productDetails.investors}</h4>
	<br>
	<h4>Địa Chỉ: {$productDetails.address}</h4>
	<br>
	<h4>Thời gian thi công: {$productDetails.time_finish}</h4>
	<br>
	<h4>Diện Tích: {$productDetails.unbuilt_area}</h4>
	<br>
	<h4>Thông tin dự án: {$productDetails.content}</h4>
	<br>
</div>
{include file='common/footer.phtml'}
