{include file='common/header.phtml'}
<div id="main" class="designcontainer">
</div>
<div id="wrapperslide">
 	<!-- Jssor Slider Begin -->
    <!-- You can move inline styles to css file or css block. -->
    <div id="slider1_container" style="position: relative; top: 0px; left: 0px; width: 1190px;
        height: 550px; background: #191919; overflow: hidden;">

        <!-- Loading Screen -->
        <div u="loading" style="position: absolute; top: 0px; left: 0px;">
            <div style="filter: alpha(opacity=70); opacity:0.7; position: absolute; display: block;
                background-color: #000000; top: 0px; left: 0px;width: 100%;height:100%;">
            </div>
            <div style="position: absolute; display: block; background: url({$smarty.const.IMAGES}image_gallery/loading.gif) no-repeat center center;
                top: 0px; left: 0px;width: 100%;height:100%;">
            </div>
        </div>

        <!-- Slides Container -->
        <div u="slides" style="cursor: move; position: absolute; left: 0px; top: 0px; width: 1190px; height: 450px; overflow: hidden;">
        	{foreach key=i item=image from=$productImages}
			<div>
                <img u="image" src="{$smarty.const.HOST}/upload/product/{$image.file_name}" title="{$image.description}" />
                <img u="thumb" src="{$smarty.const.HOST}/upload_thumb/product/{$image.file_name}" />
            </div>
			{/foreach}
        </div>
        
        <!-- Arrow Navigator Skin Begin -->
        <!-- Arrow Left -->
        <span u="arrowleft" class="jssora05l" style="width: 40px; height: 40px; top: 200px; left: 8px;">
        </span>
        <!-- Arrow Right -->
        <span u="arrowright" class="jssora05r" style="width: 40px; height: 40px; top: 200px; right: 8px">
        </span>
        <!-- Arrow Navigator Skin End -->
        
        <!-- Thumbnail Navigator Skin Begin -->
        <div u="thumbnavigator" class="jssort01" style="position: absolute; width: 1190px; height: 100px; left:0px; bottom: 0px;">
            <!-- Thumbnail Item Skin Begin -->
            <div u="slides" style="cursor: move;">
                <div u="prototype" class="p" style="position: absolute; width: 72px; height: 72px; top: 0; left: 0;">
                    <div class=w>
						<thumbnailtemplate style=" width: 100%; height: 100%; border: none;position:absolute; top: 0; left: 0;"></thumbnailtemplate></div>
                    <div class=c>
                    </div>
                </div>
            </div>
            <!-- Thumbnail Item Skin End -->
        </div>
        <!-- Thumbnail Navigator Skin End -->
        
        <!-- Trigger -->
        <script>
            jssor_slider1_starter('slider1_container');
        </script>
    </div>
    <!-- Jssor Slider End -->
</div>
<div id="main" class="container">
	<br>
	<h2>Dự Án: {$productDetails.product_name}<hr></h2>
	<br>
	<h4>Chủ Dự Án: {$productDetails.investors}</h4>
	<br>
	<h4>Địa Chỉ: {$productDetails.address}</h4>
	<br>
	<h4>Thời gian thi công: {$productDetails.time_finish}</h4>
	<br>
	<h4>Diện Tích: {$productDetails.unbuilt_area}</h4>
	<br>
	<h4>Thông tin dự án: {$productDetails.content}</h4>
	<br>
</div>
</div>
{include file='common/footer.phtml'}
