{include file='common/header.tpl'}

<form name="frmPromotion" id="frmPromotion" action="{$smarty.const.HOST_ADMIN}/promotion/dosaveedit" method="post" enctype="multipart/form-data">
<input type="hidden" value="{$arrDetail.id}" name="txtId" />
<input type="hidden" name="btSave" value="save"/>
<table width="100%" border="0" cellpadding="0" cellspacing="1">
	<tr class="label_title">
		<td colspan="2">Cập nhật Khuyến Mãi</td>
	</tr>
	<tr class="login">
		<td width="20%">Tên khuyến mãi:<span class="alert">*</span></td>
		<td width="870%"><input type="text" id="txt_name" name="txt_name" class="input" maxlength="255" value="{$arrDetail.name}" />
		</td>
	</tr>
	<tr class="login">
		<td width="20%">Nội dung khuyến mãi:</td>
		<td width="870%">
			<textarea id="txt_content" name="txt_content" style="width:95%;">{$arrDetail.content}</textarea>
		{literal}
		<script type="text/javascript">			
			CKEDITOR.replace( 'txt_content' ,
			{				
				extraPlugins : 'devtools'				
			});
		</script>
		{/literal}
		</td>
	</tr>
	<tr class="login">
		<td width="30%">Thứ tự:<span class="alert">*</span></td>
		<td width="70%"><input type="text" id="txt_order" name="txt_order" value="{$arrDetail.order}" class="input" maxlength="255"/>
		</td>
	</tr>
	<tr class="login">
		<td width="30%">Cho phép hiển thị:</td>
		<td width="70%" align="left">
			{if $arrDetail.available == 1}
				<input type="checkbox" name="checkAvailable" id="availableCheck" checked/>
			{else}
				<input type="checkbox" name="checkAvailable" id="availableCheck"/>
			{/if} 
		</td>
	</tr>
	<tr class="login">
		<td colspan="2" align="center"> 							
			<input type="submit" value="Lưu" class="content_button">
			&nbsp;&nbsp;
			<input type="reset" value="Reset" class="content_button"/>
		</td>			
	</tr>
</table>	
</form>
{literal}
<script language="javascript">
$(document).ready(function() {
	$("#frmPromotion").validate({		
		errorClass	: 'errorMessage',
		errorElement: 'span',
		onfocusout	: false,
		onkeyup		: false,
		rules: {
			txtName:{
				required 				: true
			},			
			txt_sort:{
				required				: true
			},		
		},
		messages: {
			txtName:{
				required 			: 'Bạn vui lòng nhập tên khuyến mãi'
			},
			txt_sort:{
				required			: 'Bạn vui lòng nhập vị trí sắp xếp'
			}
		},
		errorPlacement: function(label, element) {
			var id = element.attr('id');
			label.insertAfter($('#' + id));					
		}
	});
});
</script>
{/literal}

{include file='common/footer.tpl'}