{include file='common/header.tpl'}
<div id="IntroduceGroup" style="display: block;">
<table width="100%" border="0" cellpadding="1" cellspacing="1">
<tr>
<td class="menubar" width="10%">
<br/>
<br/>
        <p><a href="{$smarty.const.HOST_ADMIN}/general/about" class="label_sub_menu">Tổng Quan</a> </p>
   		<p><a href="{$smarty.const.HOST_ADMIN}/general/footer" class="label_sub_menu">Thông tin Footer</a></p>
		<p><a href="{$smarty.const.HOST_ADMIN}/general/siteinfo" class="label_sub_menu">Thông tin Website</a></p>
		<p><a href="{$smarty.const.HOST_ADMIN}/general/regulation" class="label_sub_menu">Nội Quy Công Ty</a></p>
		<p><a href="{$smarty.const.HOST_ADMIN}/general/missionandvision" class="label_sub_menu">Tầm Nhìn - Sứ Mệnh</a></p>
		<p><a href="{$smarty.const.HOST_ADMIN}/general/processflow" class="label_sub_menu">Quy Trình Làm Việc</a></p>
        <p><a href="{$smarty.const.HOST_ADMIN}/general/contact" class="label_sub_menu">Liên Hệ</a></p>
</td>
<td width="90%">
