{include file='common/header.tpl'}
<div id="IntroduceGroup" style="display: block;">
<table width="100%" border="0" cellpadding="1" cellspacing="1">
<tr>
<td class="menubar" width="12%">
<br/>
<ul class="subtabs">
	<li>
    	<a class="" href="{$smarty.const.HOST_ADMIN}/general/about" title="#About">Tổng Quan</a>
    </li>
   
    <li>
   		<a class="" href="{$smarty.const.HOST_ADMIN}/general/footer" title="#Footer">Thông tin Footer</a>
    </li>
    
    <li>
    	<a class="" href="{$smarty.const.HOST_ADMIN}/general/siteinfo" title="#SiteInfo">Thông tin Website</a>
    </li>
	
    <li>
    	<a href="{$smarty.const.HOST_ADMIN}/general/regulation" title="#Regulation">Nội Quy Công Ty</a>
    </li>
	
    <li>
    	<a href="{$smarty.const.HOST_ADMIN}/general/missionandvision" title="#MissionAndVision">Tầm Nhìn - Sứ Mệnh</a>
    </li>
	
    <li>
    	<a href="{$smarty.const.HOST_ADMIN}/general/processflow" title="#ProcessFlow">Quy Trình Làm Việc</a>
    </li>
    
    <li>
    	<a href="{$smarty.const.HOST_ADMIN}/general/contact" title="#Contact">Liên Hệ</a>
    </li>
</ul>

</td>
<td width="88%">
