{include file='common/header.tpl'}
<div id="IntroduceGroup" style="display: block;">
<br/>
<br/>
<ul class="subtabs">
	<li>
    	<a class="" href="{$smarty.const.HOST_ADMIN}/general/about" title="#About">Tổng Quan</a>
    </li>
   
    <li>
   		<a class="" href="{$smarty.const.HOST_ADMIN}/general/footer" title="#Footer">Thông tin Footer</a>
    </li>
    
    <li>
    	<a class="" href="{$smarty.const.HOST_ADMIN}/general/siteinfo" title="#SiteInfo">Thông tin Website</a>
    </li>
	
    <li>
    	<a href="{$smarty.const.HOST_ADMIN}/general/regulation">Nội Quy Công Ty</a>
    </li>
	
    <li>
    	<a href="{$smarty.const.HOST_ADMIN}/general/missionandvision">Tầm Nhìn - Sứ Mệnh</a>
    </li>
	
    <li>
    	<a href="{$smarty.const.HOST_ADMIN}/general/processflow">Quy Trình Làm Việc</a>
    </li>
    
    <li>
    	<a href="{$smarty.const.HOST_ADMIN}/general/contact">Liên Hệ</a>
    </li>
</ul>
</div>
{include file='common/footer.tpl'}