{include file='general/generalheader.phtml'}
<form name="frmMissionAndVision" id="frmMissionAndVision" action="{$smarty.const.HOST_ADMIN}/general/missionandvision" method="post">
<input type="hidden" name="btSave" value="save"/>
<table width="100%" border="0" cellpadding="3" cellspacing="1">
	 <tr>
		<td align="center" class="lable_list">Nội Quy Công Ty</td>
		<td align="right"></td>
    </tr>
	{if $smarty.get.errid > 0 || $smarty.session.newsid > 0}
	<tr class="login">
		<td class="alert" colspan="2"><b>{$lang.error_news[$smarty.get.errid]}</b></td>				
	</tr>
	{/if}		
	<tr class="login">		
		<td width="100%" colspan="2">
		<textarea id="txtMissionAndVision" name="txtMissionAndVision" style="width:95%;">{$arrDetail.key_value}</textarea>
		{literal}
		<script type="text/javascript">			
			CKEDITOR.replace( 'txtMissionAndVision' ,
			{				
				extraPlugins : 'devtools'				
			});
		</script>
		{/literal}
		</td>
	</tr>	
	<tr class="login">
		<td align="center" colspan="2"> 							
			<input type="submit" value="Lưu" class="content_button">
			&nbsp;&nbsp;
			<input type="reset" value="Reset" class="content_button"/>
		</td>			
	</tr>
</table>	
</form>
{include file='general/generalfooter.phtml'}