{include file='general/generalheader.phtml'}
<form name="frmProduct" id="frmProduct" action="{$smarty.const.HOST_ADMIN}/configsite" method="post">
<input type="hidden" name="btSave" value="save"/>
<table width="100%" border="0" cellpadding="3" cellspacing="1">
	 <tr>
		<td class="lable_list">Config site SEO</td>
		<td align="right"></td>
    </tr>
	{if $smarty.get.errid > 0 || $smarty.session.newsid > 0}
	<tr class="login">
		<td class="alert" colspan="2"><b>{$lang.error_news[$smarty.get.errid]}</b></td>				
	</tr>
	{/if}		
	<tr class="login">		
		<td width="20%">Tên site<span class="alert">*</span></td>
		<td width="870%"><input type="text" id="txtTitle" name="txtTitle" class="input" maxlength="255" value="{$arrTitle.key_value}" />
		</td>
	</tr>
	<tr class="login">		
		<td width="20%">Slogan<span class="alert">*</span></td>
		<td width="870%"><input type="text" id="txtSlogan" name="txtSlogan" class="input" maxlength="255" value="{$arrSlogan.key_value}" />
		</td>
	</tr>
	<tr class="login">		
		<td width="20%">Keywords<span class="alert">*</span></td>
		<td width="870%">
			<textarea name="txtKeywords" style="width:99%;">{$arrKeywords.key_value}</textarea>
		</td>
	</tr>	
	<tr class="login">		
		<td width="20%">Description<span class="alert">*</span></td>
		<td width="870%">
			<textarea name="txtDes" style="width:99%;">{$arrDes.key_value}</textarea>
		</td>
	</tr>	
	<tr class="login">
		<td align="center" colspan="2"> 							
			<input type="submit" value="Lưu" class="content_button">
			&nbsp;&nbsp;
			<input type="reset" value="Reset" class="content_button"/>
		</td>			
	</tr>
</table>	
</form>
{include file='general/generalfooter.phtml'}