<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!--[if IE 6 ]><html class="ie ie6" xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><![endif]-->
<!--[if IE 7 ]><html class="ie ie7" xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><![endif]-->
<!--[if IE 8 ]><html class="ie ie8" xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><![endif]-->
<!--[if !IE]>-->
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<!--<![endif]-->

<head>
<link rel="shortcut icon" type="image/x-icon"
	href="{$smarty.const.IMAGES}favicon.ico" />
<title>Professional Interior Design Consult and Assitant - GrandDesign
	SaiGoin</title>
<link rel="stylesheet" href="{$smarty.const.CSS}default.css"
	type="text/css" />
<link rel="stylesheet" href="{$smarty.const.CSS}global.css"
	type="text/css" id="global_sheet" />
<link rel="stylesheet" href="{$smarty.const.CSS}buttons.css"
	type="text/css" id="buttons_sheet" />

<link rel="stylesheet" href="{$smarty.const.CSS}home.css"
	type="text/css" />
<link rel="stylesheet" href="{$smarty.const.CSS}client.css"
	type="text/css" />

<!-- <script type="text/javascript" src="{$smarty.const.JS}jquery-1.3.2.min.js"></script> -->
<script type="text/javascript" src="{$smarty.const.JS}jquery-1.11.0.js"></script>
<script type="text/javascript" src="{$smarty.const.JS}jquery-migrate.js"></script>
<script type="text/javascript"
	src="{$smarty.const.JS}jquery.ba-tinypubsub.min.js"></script>
<script type="text/javascript" src="{$smarty.const.JS}global.js"></script>
<script type="text/javascript" src="{$smarty.const.JS}jquery-form.js"></script>
<script type="text/javascript"
	src="{$smarty.const.JS}newsletterSubscription.js"></script>
<script type="text/javascript" src="{$smarty.const.JS}track.js"></script>
<script type="text/javascript" src="{$smarty.const.JS}cufon.js"></script>
<script type="text/javascript" src="{$smarty.const.JS}home.js"></script>
<script type="text/javascript" src="{$smarty.const.JS}client.js"></script>


<meta name="keywords"
	content="lighting, furniture, upholstery, textiles, sofas, accessories, tables, chairs, beds,  granddesign" />
<meta name="description"
	content="Choose from a broad range of furniture, upholstery, textiles, lighting and more at granddesign Great deals on furniture - style your home!" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="copyright" content="GrandDesign 2014" />
<meta name="robots" content="index,follow" />
<meta name="author" content="Fresca Limited" />
<meta http-equiv="imagetoolbar" content="no" />
<meta http-equiv="expires" content="now" />
<meta http-equiv="Pragma" content="no-cache" />
<meta http-equiv="Cache-control" content="no-cache" />
<meta http-equiv="content-type" content="text/html;charset=UTF-8" />
</head>

<body id="en" class="Home ly_basic">

	<div id="wrapper">
		<div id="page" class="clearfix">
			<div id="header" class="container">

				<h1 id="companyLogo">
					<img src="{$smarty.const.IMAGES}logo.png" alt="Granddesig" />
				</h1>
				<ul id="header_actions">

					<li id="header_links">
						<div id="mini_basket">
							<div id="mini_basket_heading">
								<a href="pws/ShippingOptions.html"> <span
									class="mini_basket_title">My basket</span> <span
									class="mini_basket_qty jsshow">&nbsp;</span> <span
									class="mini_basket_total jsshow">&nbsp;</span>
								</a>
							</div>
						</div>
						<ul id="header_content_links" class="content_links">
							<li class="no_js_account"><a
								href="pws/secure/ManageAccount0a41.html?secure_from=login">My
									account</a></li>
						</ul>

					</li>
					<li>
						<form action="http://google.com.vn" method="get"
							class="search_form" id="header_search_form">
							<fieldset>
								<input type="hidden" name="productsPerPage" value="20" /> <input
									accesskey="4" name="keywords" type="text" id="keywords"
									value="Search" class="text clear_value lowercase searchbox" />
								<input type="image" class="submit img"
									src="{$smarty.const.IMAGES}buttons/en/btn_magnify_search.gif"
									value="Submit" />
							</fieldset>
						</form>
					</li>
				</ul>
			</div>
			<div id="navigation" class="container">
				<a id="navigation_content" name="navigation_content"></a>
				<ul id="main_navigation_level_1">
					<li id="nav_homepage" class="level_1 first"><a class="level_1"
						href="{$smarty.const.HOST}">Trang Chủ</a></li>
					<li id="nav_introduce" class="level_1"><a class="level_1" href="#">Giới
							Thiệu</a>
						<ul class="main_navigation_level_2 level_2_children_1">
							<li id="nav_introduce_overview_" class="level_2 first"><a
								class="level_2" href="#">Tổng Quan</a></li>
							<li id="nav_introduce_overview_" class="level_2"><a
								class="level_2" href="#">Tầm Nhìn - Sứ Mệnh</a></li>
							<li id="nav_introduce_overview_" class="level_2"><a
								class="level_2" href="#">Qui Trình Làm Việc</a></li>
							<li id="nav_introduce_overview_" class="level_2"><a
								class="level_2" href="#">Nội Quy</a></li>
							<li id="nav_introduce_overview_" class="level_2 last"><a
								class="level_2" href="#">Bảng Giá</a></li>
						</ul></li>
					<li id="nav_news" class="level_1"><a class="level_1" href="#">Tin
							Tức</a></li>
					<li id="nav_project" class="level_1"><a class="level_1" href="#">Dự
							Án</a>
						<ul class="main_navigation_level_2 level_2_children_1">
							<li id="nav_project_interior"
								class="level_2 first last counter_1"><a class="level_2" href="#">Nội
									Thất</a>
								<ul class="main_navigation_level_3">
									<li id="nav_project_interior_aparment" class="level_3 first"><a
										class="level_3" href="{$smarty.const.HOST}projects">Chung cư</a></li>
									<li id="nav_project_interior_house" class="level_3"><a
										class="level_3" href="{$smarty.const.HOST}projects">Nhà Phố</a></li>
									<li id="nav_project_interior_villa" class="level_3"><a
										class="level_3" href="{$smarty.const.HOST}projects">Biệt Thự</a></li>
									<li id="nav_project_interior_office" class="level_3"><a
										class="level_3" href="{$smarty.const.HOST}projects">Văn Phòng</a></li>
									<li id="nav_project_interior_hotel" class="level_3 last"><a
										class="level_3" href="{$smarty.const.HOST}projects">Nhà Hàng, Khách Sạn, Spa</a></li>
								</ul></li>
							<li id="nav_project_architect" class="level_2"><a class="level_2"
								href="#">Kiến Trúc</a></li>
							<li id="nav_project_realImgs" class="level_2"><a class="level_2"
								href="#">Ảnh Thực Tế</a></li>
						</ul></li>
					<li id="nav_geomancy" class="level_1"><a class="level_1" href="#">Phong
							Thủy</a></li>
					<li id="nav_woods" class="level_1"><a class="level_1" href="#">Vật
							Liệu</a>
						<ul class="main_navigation_level_2 level_2_children_1">
							<li id="nav_woods_industrialWood"
								class="level_2 first last counter_1"><a class="level_2" href="#">Gỗ
									Công Nghiệp</a>
								<ul class="main_navigation_level_3">
									<li id="nav_woods_industrialWood_mdf" class="level_3 first"><a
										class="level_3" href="#">MDF</a></li>
									<li id="nav_woods_industrialWood_mfc" class="level_3"><a
										class="level_3" href="#">MFC</a></li>
									<li id="nav_woods_industrialWood_pollywood" class="level_3"><a
										class="level_3" href="#">Polly Wood</a></li>
									<li id="nav_woods_industrialWood" class="level_3"><a
										class="level_3" href="#">Văn Phòng</a></li>
									<li id="nav_woods_industrialWood_facialCover" class="level_3"><a
										class="level_3" href="#">Vật Liệu Phủ Bề Mặt</a></li>
								</ul></li>
							<li id="nav_woods_naturalWoods" class="level_2 last"><a
								class="level_2" href="#">Kiến Trúc</a></li>
						</ul></li>
					<li id="nav_clip" class="level_1"><a class="level_1" href="#">Clips</a>
					</li>
					<li id="nav_blog" class="level_1"><a class="level_1" href="#">Blogs</a>
						<ul class="main_navigation_level_2 level_2_children_1">
							<li id="nav_blog_facebook" class="level_2 first"><a
								class="level_2" href="#">Facebook</a></li>
							<li id="nav_blog_googleplus" class="level_2 last"><a
								class="level_2" href="#">Google Plus</a></li>
						</ul></li>
					<li id="nav_recruitment" class="level_1"><a class="level_1"
						href="#">Tuyển Dụng</a>
						<ul class="main_navigation_level_2 level_2_children_1">
							<li id="nav_recruitment_info" class="level_2 first"><a
								class="level_2" href="#">Thông Tin Tuyển Dụng</a></li>
							<li id="nav_recruitment_policies" class="level_2 last"><a
								class="level_2" href="#">Chính Sách Đào Tạo</a></li>
						</ul></li>
					<li id="nav_contact" class="level_1"><a class="level_1" href="#">Liên
							Hệ</a></li> {literal}
					<script type="text/javascript">
				//creates the SUB2 script include Asynchronously 
					var _sub2_JSCODE = document.createElement('script');
					_sub2_JSCODE.type = 'text/javascript';
					_sub2_JSCODE.async = true;
					_sub2_JSCODE.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'webservices.sub2tech.com/habitat/sub2.js';
					var s = document.getElementsByTagName('script')[0];
					s.parentNode.insertBefore(_sub2_JSCODE,s);
					function _SUB2_Code() 
					{
						S2Tech_2Prompt(); 
					}
					if( _sub2_JSCODE.readyState ) 
					{
						_sub2_JSCODE.onreadystatechange = function() {
							if ( _sub2_JSCODE.readyState == 'complete' || _sub2_JSCODE.readyState == 'loaded' ) {
								try {
										_SUB2_Code(); 
								}
								catch (e) {}
       						}
     					};
					}
					else {
						_sub2_JSCODE.onload = function() {
						try {
							_SUB2_Code();
						}
						catch (e) {}
      	 				};
      				}
				</script>
					{/literal}
				</ul>
			</div>