<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="shortcut icon" type="image/x-icon" href="{$smarty.const.IMAGES}favicon.ico" />
<title>Professional Interior Design Consult and Assitant - GrandDesign SaiGon</title>

<link rel="stylesheet" href="{$smarty.const.CSS}default.css" type="text/css" />
<link rel="stylesheet" href="{$smarty.const.CSS}global.css" type="text/css" id="global_sheet" />
<link rel="stylesheet" href="{$smarty.const.CSS}buttons.css" type="text/css" id="buttons_sheet" />
<link rel="stylesheet" href="{$smarty.const.CSS}home.css" type="text/css" />
<link rel="stylesheet" href="{$smarty.const.CSS}client.css" type="text/css" />
<link rel="stylesheet" href="{$smarty.const.CSS}projectDesignSlide.css" type="text/css" />
<link type='text/css' rel='stylesheet' href='{$smarty.const.CSS}panel/panel1.css' />
<link type='text/css' rel='stylesheet' href='{$smarty.const.CSS}panel/panel2.css?targetBlogID=2944165896379117921&zx=1a6ba82d-98dc-4d07-a850-c5ab9e2e1252' />
<link type='text/css' rel='stylesheet' href='{$smarty.const.CSS}image_gallery_css/image_gallery.css' />
	
<script type="text/javascript" src="{$smarty.const.JS}jquery-1.11.0.js"></script>
<script type="text/javascript" src="{$smarty.const.JS}jquery-migrate.js"></script>
<script type="text/javascript" src="{$smarty.const.JS}global.js"></script>
<script type="text/javascript" src="{$smarty.const.JS}home.js"></script>
<script type="text/javascript" src="{$smarty.const.JS}client.js"></script>
<script type="text/javascript" src="{$smarty.const.JS}projectDesignSlide.js"></script>
<script style="text/javascript" src="{$smarty.const.JS}panel/recentpostticker.js" ></script>
<script style="text/javascript" src="{$smarty.const.JS}panel/recentpostswiththumbnailsv3.js"></script>
<script style="text/javascript" src="{$smarty.const.JS}panel/panel.js" ></script>
<script type="text/javascript" src="{$smarty.const.JS}image_gallery_js/jssor.slider.min.js"></script>
<script type="text/javascript" src="{$smarty.const.JS}image_gallery_js/image_gallery.js"></script>



<meta name="keywords"
	content="lighting, furniture, upholstery, textiles, sofas, accessories, tables, chairs, beds,  granddesign" />
<meta name="description"
	content="Choose from a broad range of furniture, upholstery, textiles, lighting and more at granddesign Great deals on furniture - style your home!" />
<meta name="copyright" content="GrandDesign 2014" />
</head>

<body id="en" class="Home ly_basic">

	<div id="wrapper">
		<div id="page" class="clearfix">
			<div id="header" class="container">
				<h1 id="companyLogo">
					<a href="{$smarty.const.HOST}"><img src="{$smarty.const.IMAGES}logo.png" alt="Grand Design" /></a>
				</h1>
				<div id="header_actions">
					<a href={$headerPic.link}><img src="{$smarty.const.HOST}data/upload/{$headerPic.imgname}"/></a>
				</div>
			</div>
			<div id="navigation" class="container">
				<a id="navigation_content" name="navigation_content"></a>
				<ul id="main_navigation_level_1">
					<li id="nav_homepage" class="level_1 first"><a class="level_1"
						href="{$smarty.const.HOST}">Trang Chủ</a></li>
					<li id="nav_introduce" class="level_1"><a class="level_1" href="#">Giới
							Thiệu</a>
						<ul class="main_navigation_level_2 level_2_children_1">
							<li id="nav_introduce_overview_" class="level_2 first"><a
								class="level_2" href="#">Tổng Quan</a></li>
							<li id="nav_introduce_overview_" class="level_2"><a
								class="level_2" href="#">Tầm Nhìn - Sứ Mệnh</a></li>
							<li id="nav_introduce_overview_" class="level_2"><a
								class="level_2" href="#">Qui Trình Làm Việc</a></li>
							<li id="nav_introduce_overview_" class="level_2"><a
								class="level_2" href="#">Nội Quy</a></li>
							<li id="nav_introduce_overview_" class="level_2 last"><a
								class="level_2" href="#">Bảng Giá</a></li>
						</ul></li>
					<li id="nav_news" class="level_1"><a class="level_1" href="{$smarty.const.HOST}news">Tin
							Tức</a></li>
					<li id="nav_project" class="level_1"><a class="level_1" href="#">Dự
							Án</a>
						<ul class="main_navigation_level_2 level_2_children_1">
							<li id="nav_project_interior"
								class="level_2 first last counter_1"><a class="level_2" href="#">Nội
									Thất</a>
								<ul class="main_navigation_level_3">
									{foreach key=i item=type from=$projectTypes}
										<li id="nav_project_interior_aparment" class="level_3 first">
											<a class="level_3" href="{$smarty.const.HOST}projects?catId={$type.id}">{$type.category_name}</a>
										</li>
									{/foreach}
								</ul>
							</li>
							<li id="nav_project_architect" class="level_2"><a class="level_2"
								href="#">Kiến Trúc</a></li>
							<li id="nav_project_realImgs" class="level_2"><a class="level_2"
								href="#">Ảnh Thực Tế</a></li>
						</ul></li>
					<li id="nav_geomancy" class="level_1"><a class="level_1" href="#">Phong
							Thủy</a></li>
					<li id="nav_woods" class="level_1"><a class="level_1" href="#">Vật
							Liệu</a>
						<ul class="main_navigation_level_2 level_2_children_1">
							<li id="nav_woods_industrialWood"
								class="level_2 first last counter_1"><a class="level_2" href="#">Gỗ
									Công Nghiệp</a>
								<ul class="main_navigation_level_3">
									{foreach key=i item=type from=$materialTypes}
										<li id="nav_project_interior_aparment" class="level_3 first">
											<a class="level_3" href="#material?materialId={$type.id}">{$type.category_name}</a>
										</li>
									{/foreach}
								</ul></li>
							<li id="nav_woods_naturalWoods" class="level_2 last"><a
								class="level_2" href="#">Kiến Trúc</a></li>
						</ul></li>
					<li id="nav_clip" class="level_1"><a class="level_1" href="#">Clips</a>
					</li>
					<li id="nav_blog" class="level_1"><a class="level_1" href="#">Blogs</a>
						<ul class="main_navigation_level_2 level_2_children_1">
							<li id="nav_blog_facebook" class="level_2 first"><a
								class="level_2" href="#">Facebook</a></li>
							<li id="nav_blog_googleplus" class="level_2 last"><a
								class="level_2" href="#">Google Plus</a></li>
						</ul></li>
					<li id="nav_recruitment" class="level_1"><a class="level_1"
						href="#">Tuyển Dụng</a>
						<ul class="main_navigation_level_2 level_2_children_1">
							<li id="nav_recruitment_info" class="level_2 first"><a
								class="level_2" href="{$smarty.const.HOST}recruitments">Thông Tin Tuyển Dụng</a></li>
							<li id="nav_recruitment_policies" class="level_2 last"><a
								class="level_2" href="#">Chính Sách Đào Tạo</a></li>
						</ul></li>
					<li id="nav_contact" class="level_1"><a class="level_1" href="#">Liên Hệ</a></li>
				</ul>
			</div>