<div class="rightbar">
	<div class="rightbar_block">
		<h3 class='rightbar_block_title'>Dự Án Nổi Bật</h3>
		<div class='widget-content'>
		<div id="sai">
		<ul class="recent_posts_with_thumbs" style="position: absolute; margin: 0px; padding: 0px;">
			{foreach key=i item=project from=$bestProjects}
			    <li style="height: 78px;" class="clearfix">
			    	<a href="{$smarty.const.HOST}projectdesign?pid={$project.id}" target="_top">
				        <img class="recent_thumb" src="{$smarty.const.HOST}upload_thumb/product/{$project.file_name}">
			    	</a>
			        <b>
			            <a href="{$smarty.const.HOST}projectdesign?pid={$project.id}" target="_top">{$project.product_name}</a>
			        </b>
			        <br>
			            <i>{$project.introduce}</i>
			        <br>
			     </li>
			{/foreach}
		</ul>
		</div>
		</div>
	</div>
	<div class="rightbar_block">
		<h3 class="rightbar_block_title">Tin Mới</h3>
		<div class='widget-content'>
		<div id="sai1">
		<ul class="recent_posts_with_thumbs" style="position: absolute; margin: 0px; padding: 0px;">
			{foreach key=i item=news from=$hotNewsAndGeomacyEntries}
			    <li style="height: 78px;" class="clearfix">
			    	<a href="{$smarty.const.HOST}readnews?pid={$news.id}" target="_top">
				        <img class="recent_thumb" src="{$news.image}">
			    	</a>
			        <b>
			            <a href="{$smarty.const.HOST}readnews?newsId={$news.id}" target="_top">{$news.title}</a>
			        </b>
			        <br>
			            <i>{$news.summary}</i>
			        <br>
			     </li>
			{/foreach}
			</ul>
		</div>
	</div>
	</div>
	<div class="rightbar_block">
		<h3 class="rightbar_block_title">Thống kê</h3>
	</div>
</div>
</div>