{include file='common/header.tpl'}
<form name="frmNews" id="frmNews" action="{$smarty.const.HOST_ADMIN}/news/dosave" method="post" enctype="multipart/form-data">
<input type="hidden" name="btSave" value="save"/>
<table width="100%" border="0" cellpadding="0" cellspacing="1">
	<tr class="label_title">
		<td colspan="2">Thêm Tin Tức</td>
	</tr>
	<tr class="login">
		<td width="20%">Tiêu đề:<span class="alert">*</span></td>
		<td width="870%"><input type="text" id="txt_title" name="txt_title" class="input" maxlength="255" value="" />
		</td>
	</tr>
	<tr class="login">
		<td width="20%">Tóm tắt:<span class="alert">*</span></td>
		<td width="870%"><input type="text" id="txt_summary" name="txt_summary" class="input" maxlength="255" value="" />
		</td>
	</tr>
    <tr class="login">
		<td width="20%">Nội dung:<span class="alert">*</span></td>
		<td width="870%">
		<textarea id="txt_content" name="txt_content" style="width:95%;"></textarea>
		{literal}
		<script type="text/javascript">			
			CKEDITOR.replace( 'txt_content' ,
			{				
				extraPlugins : 'devtools'				
			});
		</script>
		{/literal}
		</td>
	</tr>
    <tr class="login">
		<td width="20%">Cho phép hiển thị:</td>
		<td width="80%" align="left">				
			<input type="checkbox" name="checkAvailable" id="checkAvailable" value="1" class="input"> 
		</td>
	</tr>
	<tr class="login">
		<td colspan="2" align="center"> 							
			<input type="submit" value="Lưu" class="content_button">
			&nbsp;&nbsp;
			<input type="reset" value="Reset" class="content_button"/>
		</td>			
	</tr>
</table>	
</form>
{literal}
<script language="javascript">
$(document).ready(function() {
	$("#frmNews").validate({		
		errorClass	: 'errorMessage',
		errorElement: 'span',
		onfocusout	: false,
		onkeyup		: false,
		rules: {
			txt_title:{
				required 				: true
			},			
			txt_summary:{
				required				: true
			},		
		},
		messages: {
			txt_title:{
				required 			: 'Bạn vui lòng nhập tieu de'
			},
			txt_summary:{
				required			: 'Bạn vui lòng nhập tom tat'
			}
		},
		errorPlacement: function(label, element) {
			var id = element.attr('id');
			label.insertAfter($('#' + id));
		}
	});
});
</script>
{/literal}
{include file='common/footer.tpl'}