{include file='common/header.tpl'}

<form name="frmNews" id="frmNews" action="{$smarty.const.HOST_ADMIN}/news/dosaveedit" method="post" enctype="multipart/form-data">
<input type="hidden" value="{$arrDetail.id}" name="txtId" />
<input type="hidden" name="btSave" value="save"/>
<table width="100%" border="0" cellpadding="0" cellspacing="1">
	<tr class="label_title">
		<td colspan="2">Cập nhật Tin Tức</td>
	</tr>
    <tr class="login">
		<td width="20%">Looại Tin:<span class="alert">*</span></td>
		<td width="80%">
		    <select name="type">
					<option value="1">Tin Tức</option>
					<option value="2" {if $arrDetail.newstype==2} selected="selected" {/if}>Phong Thủy</option>
			</select>
		</td>
	</tr>
	<tr class="login">
		<td width="20%">Tiêu đề:<span class="alert">*</span></td>
		<td width="80%"><input type="text" id="txt_title" name="txt_title" class="input" maxlength="255" value="{$arrDetail.title}" />
		</td>
	</tr>
	<tr class="login">
		<td width="20%">Tóm tắt:<span class="alert">*</span></td>
		<td width="80%"><input type="text" id="txt_summary" name="txt_summary" class="input" maxlength="255" value="{$arrDetail.summary}" />
		</td>
	</tr>
	<tr class="login">
		<td width="20%">Hình đại diện:<span class="alert">*</span></td>
		<td width="80%"><input type="text" id="txt_image" name="txt_image" class="input" maxlength="255" value="{$arrDetail.image}" />
		</td>
	</tr>
	<tr class="login">
		<td width="20%">Nội dung:<span class="alert">*</span></td>
		<td width="80%">
			<textarea id="txt_content" name="txt_content" style="width:95%;">{$arrDetail.content}</textarea>
		{literal}
		<script type="text/javascript">			
			CKEDITOR.replace( 'txt_content' ,
			{				
				extraPlugins : 'devtools'				
			});
		</script>
		{/literal}
		</td>
	</tr>
	<tr class="login">
		<td width="20%">Lượt xem:<span class="alert">*</span></td>
		<td width="80%"><input type="text" id="txt_view_count" name="txt_view_count" class="input" maxlength="255" value="{$arrDetail.view_count}" />
		</td>
	</tr>
	<tr class="login">
		<td width="30%">Cho phép hiển thị:</td>
		<td width="70%" align="left">
			{if $arrDetail.visible == 1}
				<input type="checkbox" name="checkAvailable" id="availableCheck" checked/>
			{else}
				<input type="checkbox" name="checkAvailable" id="availableCheck"/>
			{/if} 
		</td>
	</tr>
	<tr class="login">
		<td colspan="2" align="center"> 							
			<input type="submit" value="Lưu" class="content_button">
			&nbsp;&nbsp;
			<input type="reset" value="Reset" class="content_button"/>
		</td>			
	</tr>
</table>	
</form>
{literal}
<script language="javascript">
$(document).ready(function() {
	$("#frmPromotion").validate({		
		errorClass	: 'errorMessage',
		errorElement: 'span',
		onfocusout	: false,
		onkeyup		: false,
		rules: {
			txtName:{
				required 				: true
			},			
			txt_sort:{
				required				: true
			},		
		},
		messages: {
			txtName:{
				required 			: 'Bạn vui lòng nhập tiêu đề'
			},
			txt_sort:{
				required			: 'Bạn vui lòng nhập vị trí sắp xếp'
			}
		},
		errorPlacement: function(label, element) {
			var id = element.attr('id');
			label.insertAfter($('#' + id));					
		}
	});
});
</script>
{/literal}

{include file='common/footer.tpl'}