{include file='common/header.phtml'}
<div id="main" class="container">
<table width="100%" border="1">
  <tr>
    <td width="20%">Vị trí</td>
    <td width="80%">{$arrDetail.title}</td>
  </tr>
  <tr>
    <td>Thông tin công việc</td>
    <td>{$arrDetail.content}</td>
  </tr>
  <tr>
    <td>Hạn nộp hồ sơ</td>
    <td>{$arrDetail.deadline}</td>
  </tr>
</table>

</div>
{include file='common/panel.phtml'}
{include file='common/footer.phtml'}