{include file='productgroup/productgroupHeader.phtml'}
<form name="frmCategory" id="frmCategory" action="{$smarty.const.HOST_ADMIN}/product/dosave" method="post" enctype="multipart/form-data">
<input type="hidden" name="btSave" value="save"/>
<table width="100%" border="0" cellpadding="0" cellspacing="1">
	<tr class="label_title">
		<td colspan="2">&nbsp;&nbsp;Thêm mới công trình</td>
	</tr>
	<tr class="login">
		<td width="20%">Danh mục :<span class="alert">*</span></td>
		<td width="870%">
			<select name="cbo_Category" id="cbo_Category">
				{foreach key=i item=rRow from=$arrCategory}
				<option value="{$rRow.id}">{$rRow.category_name}</option>
				{/foreach}
			</select>
		</td>
	</tr>
	<tr class="login">
		<td width="20%">Tên công trình :<span class="alert">*</span></td>
		<td width="870%"><input type="text" id="txtName" name="txtName" class="input" maxlength="255" value="" />
		</td>
	</tr>
	<tr class="login">
		<td width="20%">Khách hàng :</td>
		<td width="870%"><input type="text" id="txtInvestors" name="txtInvestors" class="input" maxlength="255" value="" />
		</td>
	</tr>
	<tr class="login">
		<td width="20%">Địa chỉ :</td>
		<td width="870%"><input type="text" id="txtAddress" name="txtAddress" class="input" maxlength="255" value="" />
		</td>
	</tr>
	<tr class="login">
		<td width="20%">Diện tích :</td>
		<td width="870%"><input type="text" id="txtUnbuilt_Area" name="txtUnbuilt_Area" class="input" maxlength="255" value="" />
		</td>
	</tr>
	<tr class="login">
		<td width="20%">Thời gian hoàn thành :</td>
		<td width="870%"><input type="text" id="txtTime_Finish" name="txtTime_Finish" class="input" maxlength="255" value="" />
		</td>
	</tr>
	<tr class="login">
		<td width="20%">Giới Thiệu :</td>
		<td width="870%"><input type="text" id="txtIntroduce" name="txtIntroduce" class="input" maxlength="255" value="" />
		</td>
	</tr>
	<tr class="login">
		<td width="20%">Nội dung :<span class="alert">*</span></td>
		<td width="80%">
		<textarea id="txtContent" name="txtContent" style="width:95%;"></textarea>
		{literal}
		<script type="text/javascript">			
			CKEDITOR.replace( 'txtContent' ,
			{				
				extraPlugins : 'devtools'				
			});
		</script>
		{/literal}
		</td>
	</tr>
	<tr class="login">
		<td width="20%">Vị trí :<span class="alert">*</span></td>
		<td width="80%" align="left">				
			<input type="text" name="txt_sort" id="txt_sort" class="input" maxlength="255" value="0">
		</td>
	</tr>
	<tr class="login">
		<td colspan="2" align="center"> 							
			<input type="submit" value="Lưu" class="content_button">
			&nbsp;&nbsp;
			<input type="reset" value="Reset" class="content_button"/>
		</td>			
	</tr>
</table>	
</form>
{literal}
<script language="javascript">
$(document).ready(function() {
	$("#frmCategory").validate({		
		errorClass	: 'errorMessage',
		errorElement: 'span',
		onfocusout	: false,
		onkeyup		: false,
		rules: {
			txtName:{
				required 				: true
			},			
			txt_sort:{
				required				: true
			},		
		},
		messages: {
			txtName:{
				required 			: 'Bạn vui lòng nhập tên công trình vào'
			},
			txt_sort:{
				required			: 'Bạn vui lòng nhập vị trí sắp xếp vào'
			}
		},
		errorPlacement: function(label, element) {
			var id = element.attr('id');
			label.insertAfter($('#' + id));
		}
	});
});
</script>
{/literal}
{include file='productgroup/productgroupFooter.phtml'}