{include file='clipblog/clipblogheader.phtml'}

<form name="frmClips" id="frmClips" action="{$smarty.const.HOST_ADMIN}/clips/dosaveedit" method="post" enctype="multipart/form-data">
<input type="hidden" value="{$arrDetail.id}" name="txtId" />
<input type="hidden" name="btSave" value="save"/>
<table width="100%" border="0" cellpadding="0" cellspacing="1">
	<tr class="label_title">
		<td colspan="2">Cập nhật Clips</td>
	</tr>
	<tr class="login">
		<td width="20%">Mô tả:<span class="alert">*</span></td>
		<td width="870%"><input type="text" id="txt_description" name="txt_description" class="input" maxlength="255" value="{$arrDetail.description}" />
		</td>
	</tr>
	<tr class="login">
		<td width="20%">Mã Clip:<span class="alert">*</span></td>
		<td width="870%"><input type="text" id="txt_embed" name="txt_embed" class="input" maxlength="255" value="{$arrDetail.embed}" />
		</td>
	</tr>
	<tr class="login">
		<td width="30%">Cho phép hiển thị:</td>
		<td width="70%" align="left">
			{if $arrDetail.visible == 1}
				<input type="checkbox" name="checkAvailable" id="availableCheck" checked/>
			{else}
				<input type="checkbox" name="checkAvailable" id="availableCheck"/>
			{/if} 
		</td>
	</tr>
	<tr class="login">
		<td colspan="2" align="center"> 							
			<input type="submit" value="Lưu" class="content_button">
			&nbsp;&nbsp;
			<input type="reset" value="Reset" class="content_button"/>
		</td>			
	</tr>
</table>	
</form>
{include file='clipblog/clipblogfooter.phtml'}