{include file='common/header.tpl'}
<form name="frmPricetable" id="frmPricetable" action="{$smarty.const.HOST_ADMIN}/pricetable" method="post">
<input type="hidden" name="btSave" value="save"/>
<table width="100%" border="0" cellpadding="3" cellspacing="1">
    <tr>
		<td align="center" class="lable_list">Bảng Giá</td>
    </tr>
	{if $smarty.get.errid > 0 || $smarty.session.newsid > 0}
	<tr class="login">
		<td class="alert" colspan="2"><b>{$lang.error_news[$smarty.get.errid]}</b></td>				
	</tr>
	{/if}
	<tr class="login">		
		<td width="100%" colspan="2">
		<textarea id="txt_pricetable" name="txt_pricetable" style="width:95%;">{$arrDetail.key_value}</textarea>
		{literal}
		<script type="text/javascript">			
			CKEDITOR.replace( 'txt_pricetable' ,
			{				
				extraPlugins : 'devtools'				
			});
		</script>
		{/literal}
		</td>
	</tr>
    <tr class="login">
		<td align="center" colspan="2"> 							
			<input type="submit" value="Lưu" class="content_button">
		</td>			
	</tr>
</table>	
	
</form>
{literal}
<script language="javascript">
$(document).ready(function() {
	$("#frmPricetable").validate({		
		errorClass	: 'errorMessage',
		errorElement: 'span',
		onfocusout	: false,
		onkeyup		: false,
		rules: {
			txt_pricetable:{
				required 				: true
			}	
		},
		messages: {
			txt_pricetable:{
				required 			: 'Bạn vui lòng nhập thông tin bảng giá.'
			}
		},
		errorPlacement: function(label, element) {
			var id = element.attr('id');
			if (id == 'frmPricetable') {
				label.insertAfter($('#cke_txt_pricetable'));
			} else {
				label.insertAfter($('#' + id));
			}			
		}
	});
});
</script>
{/literal}
{include file='common/footer.tpl'}