{include file='common/header.tpl'}
<div id="productgroup" style="display: block;">
<table width="100%" border="0" cellpadding="1" cellspacing="1">
<tr>
<td class="menubar" width="10%">
<br />
<ul class="subtabs">
        <li>
        	<a class="" href="{$smarty.const.HOST_ADMIN}/product" class="label_sub_menu">Dự Án</a>
        </li>
        
        <li>
        	<a href="{$smarty.const.HOST_ADMIN}/category" class="label_sub_menu">Loại Dự Án</a>
        </li>
</ul>
</td>
<td width="90%">