{include file='common/header.tpl'}
<div id="productgroup" style="display: block;">
<table width="100%" border="0" cellpadding="1" cellspacing="1">
<tr>
<td class="menubar" width="10%">
<br />
<br />
        <p><a href="{$smarty.const.HOST_ADMIN}/product" class="label_sub_menu">Dự Án</a></p>
		<p><a href="{$smarty.const.HOST_ADMIN}/category" class="label_sub_menu">Loại Dự Án</a></p>
</td>
<td width="90%">