{include file='clipblog/clipblogheader.phtml'}

<form name="frmBlogs" id="frmBlogs" action="{$smarty.const.HOST_ADMIN}/blogs/dosaveedit" method="post" enctype="multipart/form-data">
<input type="hidden" value="{$arrDetail.id}" name="txtId" />
<input type="hidden" name="btSave" value="save"/>
<table width="100%" border="0" cellpadding="0" cellspacing="1">
	<tr class="label_title">
		<td colspan="2">Cập nhật Blog</td>
	</tr>
	<tr class="login">
		<td width="20%">Mô tả:<span class="alert">*</span></td>
		<td width="870%"><input type="text" id="txt_description" name="txt_description" class="input" maxlength="255" value="{$arrDetail.description}" />
		</td>
	</tr>
	<tr class="login">
		<td width="20%">Link:<span class="alert">*</span></td>
		<td width="870%"><input type="text" id="txt_link" name="txt_link" class="input" maxlength="255" value="{$arrDetail.link}" />
		</td>
	</tr>
	<tr class="login">
		<td width="30%">Cho phép hiển thị:</td>
		<td width="70%" align="left">
			{if $arrDetail.visible == 1}
				<input type="checkbox" name="checkAvailable" id="availableCheck" checked/>
			{else}
				<input type="checkbox" name="checkAvailable" id="availableCheck"/>
			{/if} 
		</td>
	</tr>
	<tr class="login">
		<td colspan="2" align="center"> 							
			<input type="submit" value="Lưu" class="content_button">
			&nbsp;&nbsp;
			<input type="reset" value="Reset" class="content_button"/>
		</td>			
	</tr>
</table>	
</form>
{literal}
<script language="javascript">
$(document).ready(function() {
	$("#frmBlogs").validate({		
		errorClass	: 'errorMessage',
		errorElement: 'span',
		onfocusout	: false,
		onkeyup		: false,
		rules: {
			txt_description:{
				required 				: true
			},			
			txt_link:{
				required				: true
			},		
		},
		messages: {
			txt_description:{
				required 			: 'Bạn vui lòng nhập mô tả'
			},
			txt_link:{
				required			: 'Bạn vui lòng nhập link'
			}
		},
		errorPlacement: function(label, element) {
			var id = element.attr('id');
			label.insertAfter($('#' + id));					
		}
	});
});
</script>
{/literal}

{include file='clipblog/clipblogfooter.phtml'}