{include file='productgroup/productgroupHeader.phtml'}

<form name="frmCategory" id="frmCategory" action="{$smarty.const.HOST_ADMIN}/category/dosaveedit" method="post" enctype="multipart/form-data">
<input type="hidden" value="{$arrDetail.id}" name="txtId" />
<input type="hidden" name="btSave" value="save"/>
<table width="100%" border="0" cellpadding="0" cellspacing="1">
	<tr class="label_title">
		<td colspan="2">Cập nhật Danh Mục</td>
	</tr>
	<tr class="login">
		<td width="20%">Loại danh mục :<span class="alert">*</span></td>
		<td width="870%">
			<select name="cbo_type" id="cbo_type">
				<option value="0" {if $arrDetail.type==0}selected="selected"{/if}>Dự Án</option>
				<option value="1" {if $arrDetail.type==1}selected="selected"{/if}>Vật Liệu - Gỗ Công Nghiệp</option>
			</select>
		</td>
	</tr>
	<tr class="login">
		<td width="30%">Tên danh mục :<span class="alert">*</span></td>
		<td width="70%"><input type="text" id="txtName" name="txtName" value="{$arrDetail.category_name}" maxlength="255"/>
		</td>
	</tr>
	<tr class="login">
		<td width="30%">Vị trí :<span class="alert">*</span></td>
		<td width="70%" align="left">				
			<input type="text" name="txt_sort" id="txt_sort" maxlength="255" value="{$arrDetail.sort}"> 
			
		</td>
	</tr>
	<tr class="login">
		<td colspan="2" align="center"> 							
			<input type="submit" value="Lưu" class="content_button">
			&nbsp;&nbsp;
			<input type="reset" value="Reset" class="content_button"/>
		</td>			
	</tr>
</table>	
</form>
{literal}
<script language="javascript">
$(document).ready(function() {
	$("#frmCategory").validate({		
		errorClass	: 'errorMessage',
		errorElement: 'span',
		onfocusout	: false,
		onkeyup		: false,
		rules: {
			txtName:{
				required 				: true
			},			
			txt_sort:{
				required				: true
			},		
		},
		messages: {
			txtName:{
				required 			: 'Bạn vui lòng nhập tên danh mục vào vào'
			},
			txt_sort:{
				required			: 'Bạn vui lòng nhập vị trí sắp xếp vào'
			}
		},
		errorPlacement: function(label, element) {
			var id = element.attr('id');
			label.insertAfter($('#' + id));					
		}
	});
});
</script>
{/literal}

{include file='productgroup/productgroupFooter.phtml'}